apiVersion: 1

datasources:
- name: TeslaMate
  type: postgres
  url: $DATABASE_HOST:$DATABASE_PORT
  user: $DATABASE_USER
  database: $DATABASE_NAME
  password: ""
  access: proxy
  basicAuth: false
  withCredentials: false
  isDefault: true
  secureJsonData:
    password: $DATABASE_PASS
  jsonData:
    postgresVersion: 1000
    sslmode: disable
  version: 1
  editable: true
- name: solardb
  type: influxdb
  url: $SOLAR_DATABASE_HOST:$SOLAR_DATABASE_PORT
  user: $SOLAR_DATABASE_USER
  database: $SOLAR_DATABASE_NAME
  password: ""
  access: proxy
  basicAuth: false
  withCredentials: false
  isDefault: false
  secureJsonData:
    password: $DATABASE_PASS
  jsonData:
    httpMode: POST
  version: 1
  editable: true
